### ISSUE TITLE
docker not starting

### ISSUE THREAD

**Issue by carlotodeschini** [agalliazzo/samsungac#3]
When I run the docker for the first time I get this error: 

```
$ docker-compose up --build -d
Creating network "samsungac_default" with the default driver
Building samsungac
Step 1/7 : FROM python:3.10-alpine
 ---> 98fb59a98736
Step 2/7 : ADD main.py /
 ---> Using cache
 ---> 6c02fb6941e1
Step 3/7 : ADD samsung_discovery.py /
 ---> Using cache
 ---> 9afd510abb96
Step 4/7 : ADD requirements.txt /
 ---> Using cache
 ---> 382481309418
Step 5/7 : ADD config.json /
ERROR: Service 'samsungac' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder101874090/config.json: no such file or directory

```
Any documentation about config.json file format?
Thanks,
tode

**Comment by agalliazzo** [comment]
Hi Carlo,
yep, json is basically a dictionary of dictionaries with the main dictionary key same as MAC address of the AC:
```JSON
{
    "AABBCCDDEEFF": {
        "mac_address": "AABBCCDDEEFF",
        "ip_address": "192.168.1.1",
        "nickname": "AC Bedroom",
        "token": "nnnnnn-nnnnn-Token-nnnn",
        "base_topic": "/some/mqtt/topic"
    }
}
```
the file can be generated running
```bash
python3 main.py -i
```
and then proceeding with the discovery procedure (option 'd')

**Comment by carlotodeschini** [comment]
Thank you agalliazzo for the quick feedback,
but now I have another problem:

```
$ python3 main.py -i
  File "main.py", line 558
    match thread_state:
          ^
SyntaxError: invalid syntax
```
and the config.json is not generated.
My python vesion is 3.8.10

**Comment by agalliazzo** [comment]
Yes, it is written for python > 3.10. 
You can build the container simply creating an empty config.json file for example by
``` bash
touch config.json
```

and then, once the container is up, you can invoke something like:
```bash
docker exec -ti <continer_id> main.py -i
```

I didn't tested the last part and I'm not a docker expert so maybe there is something wrong...

**Comment by agalliazzo** [comment]
No, ok, it didn't work... Give me some time to fix the problem...

**Comment by carlotodeschini** [comment]
OK.
If I run a console into container I get:
```
$ docker exec -it samsungac_samsungac_1 sh
/ # python3 --version
Python 3.10.8
/ # python /main.py -i
2022-11-19 09:48:05.531 INFO: Total device in conf file: 0
Traceback (most recent call last):
  File "/main.py", line 593, in <module>
    interactive()
  File "/main.py", line 503, in interactive
    air_conditioners, air_conditioner = create_interfaces()
  File "/main.py", line 493, in create_interfaces
    return acs, next(iter(acs.items()))[1]
StopIteration
/ # 
```
I'm not able ot catch the python problem...
tode

**Comment by carlotodeschini** [comment]
OK, I saw your commit. 
The problem is solved.
Now I keep going with con configuration file,
thanks
